import Head from 'next/head'
import { Inter } from '@next/font/google'

import MainNavigation from '@/components/layout/navigation/MainNavigation'
import Footer from '@/components/layout/footer/Footer'

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
})

const Register = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainNavigation className={`${inter.variable} font-sans`} />
            <main className={`${inter.variable} font-sans`}>CONTENT</main>
            <Footer className={`${inter.variable} font-sans`} />
        </>
    )
}

export default Register
