import Head from 'next/head'
import { Inter } from '@next/font/google'

import MainNavigation from '@/components/layout/navigation/MainNavigation'

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
})

const Home = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${inter.variable} font-sans`}>
                <MainNavigation />
            </main>
            <footer className='bg-red-400 w-full h-6' />
        </>
    )
}

export default Home
